- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install nodejs
  apt:
    name: nodejs
- name: Install npm
  apt:
    name: npm
- name: Install pm2
  npm:
    name: pm2
    global: yes
