- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install a list of packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Get minikube
  get_url: 
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/ubuntu/minikube-linux-amd64
- name: Install minikube
  command: install /home/ubuntu/minikube-linux-amd64 /usr/local/bin/minikube
