- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install a list of packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install a list of packages
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Add user to docker group
  ansible.builtin.user:
    name: USERNAME
    groups: docker
    append: yes
- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection
- name: Get kubectl
  get_url: 
    url: https://dl.k8s.io/release/v1.23.5/bin/linux/amd64/kubectl
    dest: /home/ubuntu/kubectl
- name: Install kubectl
  command: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
- name: Get minikube
  get_url: 
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /home/ubuntu/minikube-linux-amd64
- name: Install minikube
  command: install /home/ubuntu/minikube-linux-amd64 /usr/local/bin/minikube
- name: Run minikube
  become: no
  command: minikube start
