- name: Update apt-get repo and cache
  apt: update_cache=yes
- name: Install "pm2" node.js package.
  community.general.npm:
    name: pm2
    path: /app/location
- name: pm2 start npm -- start
  command: "pm2 start npm -- start"
