- name: add node-exporter user
  command: "useradd --no-create-home node_exporter"
- name: get node-exporter file
  command: "wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz"
- name: extract files
  command: "tar xzf node_exporter-1.0.1.linux-amd64.tar.gz"
- name: copy executables
  command: "cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter"
- name: remove files
  command: "rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64"
- name: run node_exporter
  command: "node_exporter"
